version: '3'
services:
  app:
    restart: always
    depends_on: 
      - mongo
      - mongo-seed
    build: app-server/.
    ports:
      - 4446:4446
  api:
    restart: always
    depends_on: 
      - mongo
      - mongo-seed
    build: api-server/.
    ports:
      - 4445:4445
  auth:
    restart: always
    depends_on: 
      - mongo
      - mongo-seed
    build: auth-server/.
    ports:
      - 4444:4444
  mongo-seed:
    build: mongo-seed/.
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:
